main = "worker/index.js"
compatibility_date = "2026-10-01"
name = "webcraft-ecommerce"
[[d1_databases]]
binding = "ecommerce_db"
database_name = "ecommerce-db"
database_id = "57020184-0139-43ed-b51d-ee801b6e2470"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "72a692e6be694d99b561374d655d5378"